cloud:
  aws:
    s3:
      bucket: crowdm
    credentials:
      access-key:
      secret-key:
    region:
      static: ap-northeast-2
    stack:
      auto: false
spring:
  datasource:
    hikari:
      maximum-pool-size: 4
      jdbc-url: jdbc:postgresql://aws-0-ap-northeast-2.pooler.supabase.com:6543/postgres
      username: postgres.avcxpauyvbzblogxmpej
      password: AIVLE0625aivle
    driver-class-name: org.postgresql.Driver

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error