server:
  port: 8080

spring:
  thymeleaf:
    cache: false
  profiles:
    default: dev
    include: secret_dev
  web:
    resources:
      static-locations: classpath:/static/, file:/opt/tomcat/webapps/crowdM/static/
      add-mappings: true
  jpa:
    database: postgresql
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  h2:
    console:
      enabled: false
logging:
  logging:
    config: classpath:logback/logback.xml

# 로그인 실패 횟수
login:
  fail:
    limit : 5

# 파일 경로
file_path:
  video_path: /video/upload


url:
  gcp_upload: http://34.64.251.222:5000/upload
